namespace Ozakboy.TradeKit.Abstractions;

/// <summary>
/// 查詢或撤銷條件單時使用的識別碼:交易所的條件單編號或用戶端的條件單編號,兩者擇一。
/// The identifier used to query or cancel a conditional order: either the exchange's conditional order id or the
/// client's own.
/// </summary>
/// <remarks>
/// <para>
/// 與 <see cref="OrderIdentifier"/> 分成兩個型別,而不是共用一個:條件單編號與委託編號是交易所兩套獨立
/// 的號碼,把停損單的編號拿去查一般委託只會得到「找不到」。型別分開之後,這種錯誤在編譯期就過不了。
/// This is a separate type from <see cref="OrderIdentifier"/> rather than a shared one because a conditional
/// order id and an order id are two independent numbering schemes at the exchange: looking a stop order's id up
/// through the plain order endpoint only ever returns "not found". With separate types that mistake no longer
/// compiles.
/// </para>
/// <para>
/// <see cref="ClientConditionalOrderId"/> 是條件單的冪等識別碼,地位與
/// <see cref="OrderRequest.ClientOrderId"/> 相同:送單逾時之後,它是唯一能查回「那張停損到底掛上去
/// 沒有」的線索。沒查就重送,結果是掛了兩張停損,其中一張在部位平掉之後會變成反向開倉。
/// <see cref="ClientConditionalOrderId"/> is the idempotency key for a conditional order, exactly as
/// <see cref="OrderRequest.ClientOrderId"/> is for an ordinary one: after a timeout it is the only handle back to
/// the question of whether the stop actually got placed. Resending without checking leaves two stops, and once
/// the position closes the survivor opens a new one in the opposite direction.
/// </para>
/// <para>
/// <see langword="default"/> 值是空識別碼,<see cref="IsEmpty"/> 為 <see langword="true"/>,不可用於查詢。
/// The <see langword="default"/> value is empty, reports <see cref="IsEmpty"/> as <see langword="true"/>, and must
/// not be used for a lookup.
/// </para>
/// </remarks>
public readonly record struct ConditionalOrderIdentifier
{
    private ConditionalOrderIdentifier(string? exchangeConditionalOrderId, string? clientConditionalOrderId)
    {
        ExchangeConditionalOrderId = exchangeConditionalOrderId;
        ClientConditionalOrderId = clientConditionalOrderId;
    }

    /// <summary>
    /// 交易所產生的條件單編號。以用戶端編號識別時為 <see langword="null"/>。
    /// The conditional order id generated by the exchange, or <see langword="null"/> when identifying by client
    /// id.
    /// </summary>
    public string? ExchangeConditionalOrderId { get; }

    /// <summary>
    /// 送單時由自己產生的條件單編號(冪等識別碼)。以交易所編號識別時為 <see langword="null"/>。
    /// The conditional order id generated locally at submission time, which acts as the idempotency key, or
    /// <see langword="null"/> when identifying by exchange id.
    /// </summary>
    public string? ClientConditionalOrderId { get; }

    /// <summary>
    /// 是否為空識別碼(兩個編號都沒有)。
    /// Whether the identifier is empty, meaning neither id is present.
    /// </summary>
    public bool IsEmpty => ExchangeConditionalOrderId is null && ClientConditionalOrderId is null;

    /// <summary>
    /// 以交易所的條件單編號建立識別碼。
    /// Creates an identifier from an exchange conditional order id.
    /// </summary>
    /// <param name="exchangeConditionalOrderId">
    /// 交易所條件單編號,不可為空白。The exchange conditional order id; must not be blank.
    /// </param>
    /// <returns>識別碼。The identifier.</returns>
    /// <exception cref="ArgumentException">
    /// <paramref name="exchangeConditionalOrderId"/> 為空白時擲出。
    /// Thrown when <paramref name="exchangeConditionalOrderId"/> is blank.
    /// </exception>
    public static ConditionalOrderIdentifier FromExchangeId(string exchangeConditionalOrderId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(exchangeConditionalOrderId);

        return new ConditionalOrderIdentifier(exchangeConditionalOrderId, null);
    }

    /// <summary>
    /// 以用戶端的條件單編號建立識別碼。
    /// Creates an identifier from a client conditional order id.
    /// </summary>
    /// <param name="clientConditionalOrderId">
    /// 用戶端條件單編號,不可為空白。The client conditional order id; must not be blank.
    /// </param>
    /// <returns>識別碼。The identifier.</returns>
    /// <exception cref="ArgumentException">
    /// <paramref name="clientConditionalOrderId"/> 為空白時擲出。
    /// Thrown when <paramref name="clientConditionalOrderId"/> is blank.
    /// </exception>
    public static ConditionalOrderIdentifier FromClientId(string clientConditionalOrderId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(clientConditionalOrderId);

        return new ConditionalOrderIdentifier(null, clientConditionalOrderId);
    }

    /// <summary>
    /// 回傳可讀的識別碼描述。
    /// Returns a readable description of the identifier.
    /// </summary>
    /// <returns>識別碼描述。The description.</returns>
    public override string ToString() =>
        ExchangeConditionalOrderId is not null
            ? $"conditionalOrderId={ExchangeConditionalOrderId}"
            : ClientConditionalOrderId is not null
                ? $"clientConditionalOrderId={ClientConditionalOrderId}"
                : "(empty)";
}
