namespace Ozakboy.TradeKit.Abstractions;

/// <summary>
/// 查詢或撤銷委託時使用的識別碼:交易所訂單編號或用戶端訂單編號,兩者擇一。
/// The identifier used to query or cancel an order: either the exchange order id or the client order id.
/// </summary>
/// <remarks>
/// <para>
/// 分成兩種是因為送單當下拿不到交易所編號 —— 網路逾時的那一瞬間,單可能已經進了交易所。
/// 這時唯一能用來查回那張單的線索就是自己產生的 <see cref="ClientOrderId"/>,它也是整套系統的冪等識別碼。
/// The two forms exist because the exchange id is not available at submission time: when the request times out,
/// the order may already be live. The only handle back to it is the <see cref="ClientOrderId"/> you generated
/// yourself, which is also the idempotency key for the whole system.
/// </para>
/// <para>
/// <see langword="default"/> 值是空識別碼,<see cref="IsEmpty"/> 為 <see langword="true"/>,不可用於查詢。
/// The <see langword="default"/> value is empty, reports <see cref="IsEmpty"/> as <see langword="true"/>, and must
/// not be used for a lookup.
/// </para>
/// </remarks>
public readonly record struct OrderIdentifier
{
    private OrderIdentifier(string? exchangeOrderId, string? clientOrderId)
    {
        ExchangeOrderId = exchangeOrderId;
        ClientOrderId = clientOrderId;
    }

    /// <summary>
    /// 交易所產生的訂單編號。以用戶端編號識別時為 <see langword="null"/>。
    /// The order id generated by the exchange, or <see langword="null"/> when identifying by client id.
    /// </summary>
    public string? ExchangeOrderId { get; }

    /// <summary>
    /// 送單時由自己產生的訂單編號(冪等識別碼)。以交易所編號識別時為 <see langword="null"/>。
    /// The order id generated locally at submission time, which acts as the idempotency key, or
    /// <see langword="null"/> when identifying by exchange id.
    /// </summary>
    public string? ClientOrderId { get; }

    /// <summary>
    /// 是否為空識別碼(兩個編號都沒有)。
    /// Whether the identifier is empty, meaning neither id is present.
    /// </summary>
    public bool IsEmpty => ExchangeOrderId is null && ClientOrderId is null;

    /// <summary>
    /// 以交易所訂單編號建立識別碼。
    /// Creates an identifier from an exchange order id.
    /// </summary>
    /// <param name="exchangeOrderId">交易所訂單編號,不可為空白。The exchange order id; must not be blank.</param>
    /// <returns>識別碼。The identifier.</returns>
    /// <exception cref="ArgumentException">
    /// <paramref name="exchangeOrderId"/> 為空白時擲出。
    /// Thrown when <paramref name="exchangeOrderId"/> is blank.
    /// </exception>
    public static OrderIdentifier FromExchangeId(string exchangeOrderId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(exchangeOrderId);

        return new OrderIdentifier(exchangeOrderId, null);
    }

    /// <summary>
    /// 以用戶端訂單編號建立識別碼。
    /// Creates an identifier from a client order id.
    /// </summary>
    /// <param name="clientOrderId">用戶端訂單編號,不可為空白。The client order id; must not be blank.</param>
    /// <returns>識別碼。The identifier.</returns>
    /// <exception cref="ArgumentException">
    /// <paramref name="clientOrderId"/> 為空白時擲出。
    /// Thrown when <paramref name="clientOrderId"/> is blank.
    /// </exception>
    public static OrderIdentifier FromClientId(string clientOrderId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(clientOrderId);

        return new OrderIdentifier(null, clientOrderId);
    }

    /// <summary>
    /// 回傳可讀的識別碼描述。
    /// Returns a readable description of the identifier.
    /// </summary>
    /// <returns>識別碼描述。The description.</returns>
    public override string ToString() =>
        ExchangeOrderId is not null
            ? $"exchangeOrderId={ExchangeOrderId}"
            : ClientOrderId is not null
                ? $"clientOrderId={ClientOrderId}"
                : "(empty)";
}
